name: linting

on: 'push'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository at the current branch
        uses: actions/checkout@v2
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run black formatter
        run: black --diff .
