name: tests

on: 'push'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository at the current branch
        uses: actions/checkout@v3
      - run: cd src/python
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest
